### PR TITLE
Move rendering backends to rendering directory.

### LINKED ISSUE #211: [python] glfw nameclash
The `glfw` directory in `mujoco/python/mujoco/` is causing import errors when running `render_test.py` because it clashes with the pip package `glfw`.

To reproduce this issue:

```
cd python/mujoco
python render_test.py
```

<details>
<summary>Toggle traceback</summary>

```bash
Running tests under Python 3.8.11: /Users/kevin/miniconda3/envs/mujoco/bin/python
[ RUN      ] MuJoCoRenderTest.test_can_render
[  FAILED  ] MuJoCoRenderTest.test_can_render
Exception ignored in: <function GLContext.__del__ at 0x105ccb790>
Traceback (most recent call last):
  File "/Users/kevin/miniconda3/envs/mujoco/lib/python3.8/site-packages/mujoco/render/glfw/__init__.py", line 42, in __del__
    self.free()
  File "/Users/kevin/miniconda3/envs/mujoco/lib/python3.8/site-packages/mujoco/render/glfw/__init__.py", line 35, in free
    if self._context:
AttributeError: 'GLContext' object has no attribute '_context'
[ RUN      ] MuJoCoRenderTest.test_safe_to_free_context_twice
[  FAILED  ] MuJoCoRenderTest.test_safe_to_free_context_twice
Exception ignored in: <function GLContext.__del__ at 0x105ccb790>
Traceback (most recent call last):
  File "/Users/kevin/miniconda3/envs/mujoco/lib/python3.8/site-packages/mujoco/render/glfw/__init__.py", line 42, in __del__
    self.free()
  File "/Users/kevin/miniconda3/envs/mujoco/lib/python3.8/site-packages/mujoco/render/glfw/__init__.py", line 35, in free
    if self._context:
AttributeError: 'GLContext' object has no attribute '_context'
======================================================================
ERROR: test_can_render (__main__.MuJoCoRenderTest)
MuJoCoRenderTest.test_can_render
Test that the bindings can successfully render a simple image.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "render_test.py", line 28, in setUp
    self.gl = mujoco.GLContext(640, 480)
  File "/Users/kevin/miniconda3/envs/mujoco/lib/python3.8/site-packages/mujoco/render/glfw/__init__.py", line 24, in __init__
    if not glfw.init():
AttributeError: module 'glfw' has no attribute 'init'

======================================================================
ERROR: test_safe_to_free_context_twice (__main__.MuJoCoRenderTest)
MuJoCoRenderTest.test_safe_to_free_context_twice
----------------------------------------------------------------------
Traceback (most recent call last):
  File "render_test.py", line 28, in setUp
    self.gl = mujoco.GLContext(640, 480)
  File "/Users/kevin/miniconda3/envs/mujoco/lib/python3.8/site-packages/mujoco/render/glfw/__init__.py", line 24, in __init__
    if not glfw.init():
AttributeError: module 'glfw' has no attribute 'init'

----------------------------------------------------------------------
Ran 2 tests in 0.000s

FAILED (errors=2)
```

</details>

### PR DESCRIPTION
**Pull request by kevinzakka**
Fixes #211.

### CODE REVIEW

**Review by saran-t — APPROVED** [review]

**Review by saran-t — COMMENTED** [review]
Wait, I approved this prematurely. I don't see how this fixes #211 -- the traceback provided there looks like it occurred _with_ this change applied?

**Review by saran-t — CHANGES_REQUESTED** [review]
Wait, I approved this prematurely. I don't see how this fixes https://github.com/deepmind/mujoco/issues/211 -- the traceback provided there looks like it occurred with this change applied?

**Comment by kevinzakka** [comment]
Tried again with a fresh install on main -- the bug is there, I'm certain:

```python
Running tests under Python 3.8.13: /Users/kevin/miniconda3/envs/mujoco/bin/python
[ RUN      ] MuJoCoRenderTest.test_can_render
[  FAILED  ] MuJoCoRenderTest.test_can_render
Exception ignored in: <function GLContext.__del__ at 0x101c7d670>
Traceback (most recent call last):
  File "/Users/kevin/miniconda3/envs/mujoco/lib/python3.8/site-packages/mujoco/glfw/__init__.py", line 41, in __del__
    self.free()
  File "/Users/kevin/miniconda3/envs/mujoco/lib/python3.8/site-packages/mujoco/glfw/__init__.py", line 34, in free
    if self._context:
AttributeError: 'GLContext' object has no attribute '_context'
[ RUN      ] MuJoCoRenderTest.test_safe_to_free_context_twice
[  FAILED  ] MuJoCoRenderTest.test_safe_to_free_context_twice
Exception ignored in: <function GLContext.__del__ at 0x101c7d670>
Traceback (most recent call last):
  File "/Users/kevin/miniconda3/envs/mujoco/lib/python3.8/site-packages/mujoco/glfw/__init__.py", line 41, in __del__
    self.free()
  File "/Users/kevin/miniconda3/envs/mujoco/lib/python3.8/site-packages/mujoco/glfw/__init__.py", line 34, in free
    if self._context:
AttributeError: 'GLContext' object has no attribute '_context'
======================================================================
ERROR: test_can_render (__main__.MuJoCoRenderTest)
MuJoCoRenderTest.test_can_render
Test that the bindings can successfully render a simple image.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "render_test.py", line 28, in setUp
    self.gl = mujoco.GLContext(640, 480)
  File "/Users/kevin/miniconda3/envs/mujoco/lib/python3.8/site-packages/mujoco/glfw/__init__.py", line 24, in __init__
    glfw.init()
AttributeError: module 'glfw' has no attribute 'init'

======================================================================
ERROR: test_safe_to_free_context_twice (__main__.MuJoCoRenderTest)
MuJoCoRenderTest.test_safe_to_free_context_twice
----------------------------------------------------------------------
Traceback (most recent call last):
  File "render_test.py", line 28, in setUp
    self.gl = mujoco.GLContext(640, 480)
  File "/Users/kevin/miniconda3/envs/mujoco/lib/python3.8/site-packages/mujoco/glfw/__init__.py", line 24, in __init__
    glfw.init()
AttributeError: module 'glfw' has no attribute 'init'

----------------------------------------------------------------------
Ran 2 tests in 0.001s

FAILED (errors=2)
```

**Comment by saran-t** [comment]
I think I'm missing something obvious: can you explain why this is supposed to fix the issue?

**Comment by kevinzakka** [comment]
I may be missing something too but:

If the way to run unit tests is via `python X_test.py`, then this fails specifically for `render_test.py` on main because of weird import issues with the package `glfw` and the directory `glfw` which resides in the same directory as `render_test`.

**Comment by saran-t** [comment]
Does the issue persist if you don't run the test from its own directory?

**Comment by kevinzakka** [comment]
@saran-t Yup fails in all parent directories. I think this is an artifact of how blaze runs tests?

**Pull request closed without merging**
