### PR TITLE
Make python build work with older cmake versions

### PR DESCRIPTION
**Pull request by aftersomemath**
The ability to create a interface library target with source files was introduced in cmake 3.19.

Ubuntu 20.04 ships with cmake 3.16.3. This PR changes the CMake scripts to use the older syntax, which allows the Python bindings to build on Ubuntu 20.04 systems.

https://cmake.org/cmake/help/latest/command/add_library.html#interface-libraries

### CODE REVIEW

**Comment by saran-t** [comment]
Thanks! Have you managed to successfully built the Python bindings on your machine with this change?

**Comment by aftersomemath** [comment]
Yes and I was able to run the minimal example from the docs and the render_test without errors.

Thanks for the quick response with the cmake files and mutable attribute fixes!

**Comment by saran-t** [comment]
That's good to hear!

If you would like me to merge this PR you'll need to sign the CLA per the message from google-cla above.

**Comment by aftersomemath** [comment]
Thanks for the reminder, I just signed the CLA.

**Review by saran-t — APPROVED** [review]

**Pull request closed without merging**
